SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping constraints from [dbo].[DDTestWidgetType]'
GO
ALTER TABLE [dbo].[DDTestWidgetType] DROP CONSTRAINT [PK_WidgetTypes]
GO
PRINT N'Dropping [dbo].[DDTestWidgetType]'
GO
DROP TABLE [dbo].[DDTestWidgetType]
GO

