SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping [dbo].[AnnetteTest]'
GO
DROP TABLE [dbo].[AnnetteTest]
GO
PRINT N'Dropping [dbo].[AnnetteTestNew]'
GO
DROP TABLE [dbo].[AnnetteTestNew]
GO

